"""Materialize an agent-emitted feature spec into a Python class file.

The agent returns a JSON proposal (see prompts.PROPOSE_FEATURE). We don't trust
its `compute_pseudocode` to be valid Python — instead we emit a stub class with
a `compute()` body raising NotImplementedError, which the agent then fills in
via a second pass (or via a separate tool call). For mock-agent / smoke-test
mode, the emitted file is fully runnable from a small templating set.

Files land at ``features/<name>.py`` and become register()-decorated.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any


_FEATURES_DIR = Path(__file__).resolve().parent.parent / "features"
_REJECTED_DIR = _FEATURES_DIR / "_rejected"
_DRAFTS_DIR = _FEATURES_DIR / "_drafts"


@dataclass
class FeatureProposal:
    name: str
    description: str
    biological_motivation: str
    required_evidence: list[str]
    compute_pseudocode: str
    tool_plan: list[dict[str, Any]]

    @classmethod
    def from_json(cls, raw: str | dict) -> "FeatureProposal":
        data = json.loads(raw) if isinstance(raw, str) else raw
        return cls(
            name=data["name"],
            description=data.get("description", ""),
            biological_motivation=data.get("biological_motivation", ""),
            required_evidence=list(data.get("required_evidence", [])),
            compute_pseudocode=data.get("compute_pseudocode", ""),
            tool_plan=list(data.get("tool_plan", [])),
        )


_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def _validate_name(name: str) -> None:
    if not _NAME_RE.match(name):
        raise ValueError(f"feature name must be snake_case: {name!r}")
    if name in {"base", "registry"}:
        raise ValueError(f"reserved feature name: {name!r}")


def _class_name(snake: str) -> str:
    return "".join(part.capitalize() for part in snake.split("_")) + "Feature"


_TEMPLATE = '''"""Auto-generated by feature_writer. Stage v{stage_index}.

Description: {description}

Biological motivation:
{biological_motivation}
"""
from __future__ import annotations

from ..evidence.envelope import PairEvidence
from ..pair import ReceptorPair
from .base import Feature
from .registry import register


@register
class {class_name}(Feature):
    name = "{name}"
    version = "1.0"
    description = {description!r}
    required_evidence = {required_evidence!r}

    def compute(self, pair: ReceptorPair, ev: PairEvidence) -> float | None:
        # Compute hint (agent-provided pseudocode):
        # {compute_pseudocode_lines}
{compute_body}
'''


def _stub_compute_body(proposal: FeatureProposal) -> str:
    """Default compute: sum of normalized evidence values, missing keys → None."""
    if not proposal.required_evidence:
        return "        return None  # NOTE: no required_evidence declared\n"
    body = ['        vals = []']
    body.append('        for k in self.required_evidence:')
    body.append('            v = ev.get(k)')
    body.append('            if v is None:')
    body.append('                continue')
    body.append('            try:')
    body.append('                vals.append(float(v))')
    body.append('            except (TypeError, ValueError):')
    body.append('                continue')
    body.append('        if not vals:')
    body.append('            return None')
    body.append('        return sum(vals) / len(vals)')
    return "\n".join(body) + "\n"


def materialize(
    proposal: FeatureProposal,
    *,
    stage_index: int,
    out_dir: Path | None = None,
    compute_body: str | None = None,
) -> Path:
    out_dir = out_dir or _FEATURES_DIR
    _validate_name(proposal.name)
    target = out_dir / f"{proposal.name}.py"
    if target.exists():
        raise FileExistsError(f"feature already exists: {target}")

    body = compute_body or _stub_compute_body(proposal)
    pseudocode_lines = "\n        # ".join(proposal.compute_pseudocode.splitlines() or [""])

    src = _TEMPLATE.format(
        stage_index=stage_index,
        description=proposal.description,
        biological_motivation=proposal.biological_motivation,
        class_name=_class_name(proposal.name),
        name=proposal.name,
        required_evidence=tuple(proposal.required_evidence),
        compute_pseudocode_lines=pseudocode_lines,
        compute_body=body,
    )
    target.write_text(src)
    return target


def archive(path: Path, *, reason: str = "") -> Path:
    _REJECTED_DIR.mkdir(parents=True, exist_ok=True)
    dest = _REJECTED_DIR / path.name
    if dest.exists():
        dest = _REJECTED_DIR / f"{path.stem}__retry.py"
    path.rename(dest)
    if reason:
        (_REJECTED_DIR / f"{dest.stem}.reason.txt").write_text(reason)
    return dest
